name: Weekday

on:
#  schedule: # 03:00 JST == 18:00 UTC
#    - cron: "0 18 * * *"
  workflow_dispatch:
  
permissions: write-all  

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    name: generate chart
    steps:
     - name: install curl
       run: sudo apt-get install -y libcurl4-openssl-dev

     - name: Set up R
       uses: r-lib/actions/setup-r@v2
       with:
        r-version: 4.x
        use-public-rspm: true


     - name: Dependencies
       run: Rscript -e "install.packages(c('curl','gh','dplyr','ggplot2','viridis'))"
     - name: Checkout repository
       uses: actions/checkout@v2
       with:
          repository: brandmaier/weekdaychart
          ref: main  # specify the branch 
        
     - name: Generate graph
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          REPOSITORY: ${{ github.event.repository.name }}
       run: |
          Rscript chart.R

     - name: Commit & Push
       run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -am "updated weekday chart"
          git push
